apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  labels:
    name: ${SERVICE_NAME}
spec:
  ports:
    - name: http
      port: ${SERVICE_PORT}
      targetPort: ${SERVICE_PORT}
  selector:
    app: ${SERVICE_NAME}
